In [2]:
import pandas as pd

df = pd.read_csv("../output/raw_csv/17_party_list.csv")
print(df.shape)
print(df.dtypes)
print()
df.head(20)

(503, 9)
จังหวัด             object
เขต                  int64
ชุดที่             float64
บัตรดี             float64
บัตรเสีย           float64
บัตรที่ไม่เลือก    float64
หมายเลข              int64
พรรค                object
คะแนน              float64
dtype: object

,จังหวัด,เขต,ชุดที่,บัตรดี,บัตรเสีย,บัตรที่ไม่เลือก,หมายเลข,พรรค,คะแนน
0,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,1,1,0.0
1,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,2,2,2.0
2,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,3,3,0.0
3,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,4,4,0.0
4,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,5,5,0.0
5,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,6,6,7.0
6,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,7,7,1.0
7,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,8,8,1.0
8,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,9,9,6.0
9,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,10,10,2.0
10,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,11,11,5.0
11,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,12,12,2.0
12,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,13,13,2.0
13,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,14,14,0.0
14,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,15,15,0.0
15,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,16,16,0.0
16,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,17,17,0.0
17,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,18,18,0.0
18,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,19,19,0.0
19,นครศรีธรรมราช,2,3.0,NaN,NaN,NaN,20,20,0.0

In [3]:

party_ref = pd.read_csv("../reference/party_list_ref.csv", dtype={"หมายเลข": int})

# Map หมายเลข → ชื่อพรรค
party_map = dict(zip(party_ref["หมายเลข"], party_ref["พรรค"]))
df["พรรค"] = df["หมายเลข"].map(party_map)

print(df[["หมายเลข", "พรรค", "คะแนน"]].head(20))
print("null พรรค:", df["พรรค"].isna().sum())

    หมายเลข                  พรรค  คะแนน
0         1      พรรคไทยทรัพย์ทวี    0.0
1         2      พรรคเพื่อชาติไทย    2.0
2         3              พรรคใหม่    0.0
3         4          พรรคมิติใหม่    0.0
4         5          พรรครวมใจไทย    0.0
5         6   พรรครวมไทยสร้างชาติ    7.0
6         7             พรรคพลวัต    1.0
7         8   พรรคประชาธิปไตยใหม่    1.0
8         9          พรรคเพื่อไทย    6.0
9        10      พรรคทางเลือกใหม่    2.0
10       11          พรรคเศรษฐกิจ    5.0
11       12        พรรคเสรีรวมไทย    2.0
12       13    พรรครวมพลังประชาชน    2.0
13       14        พรรคท้องที่ไทย    0.0
14       15          พรรคอนาคตไทย    0.0
15       16      พรรคพลังเพื่อไทย    0.0
16       17            พรรคไทยชนะ    0.0
17       18     พรรคพลังสังคมใหม่    0.0
18       19  พรรคสังคมประชาธิปไตย    0.0
19       20            พรรคฟิวชัน    0.0
null พรรค: 0

In [4]:
df.head()

,จังหวัด,เขต,ชุดที่,บัตรดี,บัตรเสีย,บัตรที่ไม่เลือก,หมายเลข,พรรค,คะแนน
0,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,1,พรรคไทยทรัพย์ทวี,0.0
1,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,2,พรรคเพื่อชาติไทย,2.0
2,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,3,พรรคใหม่,0.0
3,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,4,พรรคมิติใหม่,0.0
4,นครศรีธรรมราช,2,1.0,NaN,NaN,NaN,5,พรรครวมใจไทย,0.0

In [5]:
df.to_csv("../output/cleaned/17_party_list.csv", index=False, encoding="utf-8-sig")
print(f"✅ Export {len(df)} rows → output/cleaned/17_party_list.csv")

✅ Export 503 rows → output/cleaned/17_party_list.csv